from backend.celery.celery_worker import celery_app
from backend.celery.emailer import send_email
from datetime import datetime
from backend import config

@celery_app.task(name="tasks.send_reset_email")
def send_reset_email(to_email, reset_link):
    subject = "Password Reset Request"
    body = f"Click here to reset your password: {reset_link}\n\nThis link will expire in 15 minutes."
    send_email(to_email, subject, body)

@celery_app.task(name="tasks.send_invite_email")
def send_invite_email(to_email, invite_link):
    subject = "You are invited to join the organization"
    body = f"You have been invited to join the organization on BrandPulse.\n\nClick here to set your password and join: {invite_link}\n\nThis link will expire in 15 minutes."
    send_email(to_email, subject, body)

@celery_app.task(name="tasks.send_sentiment_alert")
def send_sentiment_alert(to_email, brand_name, alert_type, breakdown, sample_posts, timestamp_str):
    color_label = "🔴 NEGATIVE" if alert_type == "HIGH_NEGATIVE" else "🟢 POSITIVE"
    subject = f"[Alert] {color_label} Sentiment Spike Detected for {brand_name}"

    sample_block = "\n".join([f"  - {p[:200]}" for p in sample_posts[:5]])
    body = f"""
BrandPulse Sentiment Alert — {timestamp_str}
Brand: {brand_name}
Alert Type: {alert_type}

===  Sentiment Breakdown (Last 12 Hours) ===
  🟢 Positive:  {breakdown.get('positive_pct', 0):.1f}%
  🔴 Negative:  {breakdown.get('negative_pct', 0):.1f}%
  🔵 Neutral:   {breakdown.get('neutral_pct', 0):.1f}%

=== Sample Posts ===
{sample_block}

---
This alert was automatically generated by BrandPulse.
"""
    send_email(to_email, subject, body)


@celery_app.task(name="tasks.send_low_credit_alert")
def send_low_credit_alert(to_email, brand_name, credits_left, inactive_org_count):
    subject = f"Low credits warning for {brand_name}"
    body = f"""
BrandPulse Billing Notice

Organization: {brand_name}
Current account credits: {credits_left}
Inactive organizations under this owner: {inactive_org_count}

When credits drop below 100, owned organizations become inactive.
Inactive organizations consume 0 credits and all data processing stops until they are reactivated.

Please top up credits and reactivate organizations as needed.
"""
    send_email(to_email, subject, body)


@celery_app.task(name="tasks.send_data_purge_alert")
def send_data_purge_alert(to_email, brand_name):
    subject = f"Organization inactive for {brand_name}"
    body = f"""
BrandPulse Billing Critical Notice

Organization: {brand_name}

The organization is inactive due to insufficient credits.
Inactive organizations do not consume credits and all processing is stopped until reactivation.

If this was unexpected, contact support immediately.
"""
    send_email(to_email, subject, body)


@celery_app.task(name="tasks.send_account_deletion_feedback")
def send_account_deletion_feedback(user_email, feedback_text):
    subject = f"[BrandPulse Feedback] Account deleted by {user_email}"
    feedback = (feedback_text or "").strip() or "No feedback provided."
    body = f"""
BrandPulse Account Deletion Feedback

User: {user_email}
Deleted at: {datetime.utcnow().isoformat()}Z

Feedback:
{feedback}
"""
    send_email(to_email=config.DEFAULT_FROM_EMAIL, subject=subject, body=body)


@celery_app.task(name="tasks.send_organization_deletion_email")
def send_organization_deletion_email(owner_email, org_details):
    subject = f"[BrandPulse Notice] Organization deleted: {org_details.get('name', 'Unknown')}"
    body = f"""
BrandPulse Organization Deletion Notice

Owner: {owner_email}
Deleted at: {datetime.utcnow().isoformat()}Z

Organization details:
- ID: {org_details.get('id')}
- Name: {org_details.get('name')}
- Brand Name: {org_details.get('brand_name')}
- Keywords: {org_details.get('keywords')}
- Status before delete: {'Active' if org_details.get('is_active') else 'Inactive'}
"""
    send_email(to_email=owner_email, subject=subject, body=body)